# Generated by Django 4.1.7 on 2023-07-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_20230326_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, default='static/images\\default.jpg', null=True, upload_to='images/Guide/'),
        ),
    ]
