# Generated by Django 4.1.7 on 2023-07-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_guide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Guide/'),
        ),
    ]
